language: python
python:
 - "3.8"
services:
  - mongodb
install:
    - pip install -r backend/requirements.txt
    - pip install -r test/requirements.txt
before_script:
- sleep 15
- mongo tracker --eval 'db.createUser({user:"tracker",pwd:"tracker",roles:["readWrite"]});'
script:
    - test/travis_script.sh
