version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-database
    restart: on-failure
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    depends_on:
      - db
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /code
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /code
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile-proxy
    ports:
      - 5000:80
    depends_on:
      - backend
      - frontend