FROM ubuntu:18.04

ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip

ADD . /code
COPY settings.yaml.sample /settings.yaml
RUN sed -i 's/mongo_host:.*/mongo_host: "db"/' /settings.yaml
WORKDIR /code

ENV FLASK_APP backend/app.py
ENV FLASK_DEBUG 1

RUN pip3 install -r backend/requirements.txt

CMD ["flask", "run", "--host", "0.0.0.0"]
