FROM python:latest

ADD . /code
COPY config.yaml.sample /config.yaml
RUN sed -i 's/mongo_host:.*/mongo_host: "db"/' /config.yaml
WORKDIR /code/backend

ENV PYTHONPATH /code/backend

RUN pip3 install -r requirements.txt

CMD ["python3", "app.py", "--config_file", "/config.yaml"]
