FROM node:alpine

RUN yarn global add @quasar/cli

COPY ./quasar/package.json /package.json
RUN yarn install

ADD ./quasar  /code/
WORKDIR /code

RUN rm -rf /code/node_modules
RUN mv /node_modules /code/

CMD ["quasar", "dev"]
