FROM node:alpine

RUN yarn global add @quasar/cli

COPY ./frontend/package.json /package.json
RUN yarn install

ADD ./frontend  /code/
WORKDIR /code

RUN rm -rf /code/node_modules
RUN mv /node_modules /code/

CMD ["quasar", "dev"]
