FROM node:alpine as build

RUN yarn global add @quasar/cli

COPY ./quasar/package.json /package.json
WORKDIR /
RUN yarn install

COPY ./quasar /code
RUN mv /node_modules /code/
WORKDIR /code/
RUN quasar build


FROM nginx:alpine

COPY --from=build /code/dist/ /usr/share/nginx/html/
COPY ./k8s/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
