FROM python:alpine

COPY ./backend/ /code/
WORKDIR /code/

ENV PYTHONPATH /code

RUN pip3 install -r /code/requirements.txt

# Must mount the file /config.yaml before starting

CMD ["gunicorn", "-w", "3", "-k", "gthread", "--bind", "0.0.0.0:8000", "app:app"]
