FROM node:alpine as build

COPY ./frontend/package.json /package.json

WORKDIR /

RUN yarn install

COPY ./frontend /code

RUN mv /node_modules /code/

WORKDIR /code/

RUN yarn build



FROM nginx:alpine

COPY --from=build /code/dist/ /usr/share/nginx/html/

COPY ./k8s/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
