FROM python:alpine

COPY ./backend/ /code/
WORKDIR /code

ENV PYTHONPATH /code

RUN pip3 install -r /code/requirements.txt

# Must mount the file /config/config.yaml before starting

CMD ["python3", "app.py", "--config_file", "/config/config.yaml"]
