FROM python:3.9-alpine

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev rust cargo

COPY ./backend/requirements.txt /requirements.txt

RUN pip3 install -r /requirements.txt

ADD . /code
COPY config.yaml.sample /config.yaml
RUN sed -i 's/host:.*/host: "db"/' /config.yaml
RUN sed -i 's/api: false/api: true/' /config.yaml
RUN sed -i 's/testing: false/testing: true/' /config.yaml
WORKDIR /code/backend

ENV PYTHONPATH /code/backend

CMD ["python3", "app.py", "--config_file", "/config.yaml"]
