<template>
<q-page class="q-pa-sm">
  <div class="text-center q-mb-xl">
    <h1 class="text-h2">SciLifeLab Data Tracker</h1>
    <div class="text-h5">
      A system for tracking data generated by SciLifeLab facilities.
    </div>
  </div>
  <div class="row flex flex-center">
    <div class="col-md-4 col-lg-4 col-xs-10 col-sm-10"
         v-if="currentUser.permissions.includes('DATA_EDIT')">
      <q-card class="q-pa-lg text-center box-shadow q-ma-md"
              id="index-card-orders"
              @click="$router.push({ name: 'Order Browser' })">
	<q-card-section>
          <q-icon size="150px" name="assignment" style="color: #045C64;"/>
          <div class="q-mt-lg text-h5 text-weight-bold">Orders</div>
        </q-card-section>
      </q-card>
    </div>
    <div class="col-md-4 col-lg-4 col-xs-10 col-sm-10">
      <q-card class="q-pa-lg text-center box-shadow q-ma-md"
              id="index-card-datasets"
              @click="$router.push({ name: 'Dataset Browser' })">
	<q-card-section>
          <q-icon size="150px" name="fas fa-chart-area" style="color: #045C64;"/>
          <div class="q-mt-lg text-h5 text-weight-bold">Datasets</div>
        </q-card-section>
      </q-card>
    </div>
    <div class="col-md-4 col-lg-4 col-xs-10 col-sm-10">
      <q-card class="q-pa-lg text-center box-shadow q-ma-md"
              id="index-card-collections"
              @click="$router.push({ name: 'Collection Browser' })">
	<q-card-section>
          <q-icon size="150px" name="fas fa-layer-group" style="color: #045C64;" />

          <div class="q-mt-lg text-h5 text-weight-bold">Collections</div>
        </q-card-section>
      </q-card>
    </div>
    <div class="row col-md-6 col-xs-10 q-mx-sm q-my-lg flex flex-center">
      <q-input class="col-9"
               rounded
               outlined
               dense
               v-model="searchEntry"
               placeholder="Entry identifier"
               @keyup.enter="findEntry"/>
      <q-btn class="q-ml-md col-2"
             rounded
             :color="searchError ? 'negative' : 'primary'"
             type="submit"
             @click="findEntry">
        Find entry
      </q-btn>
    </div>
  </div>
</q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  computed: {
    currentUser: {
      get () {
        return this.$store.getters['currentUser/info'];
      },
    },
  },

  data () {
    return {
      searchEntry: '',
      searchError: false,
    }
  },

  methods: {
    findEntry() {
      let target = ''
      if (this.searchEntry.slice(0, 2) == 'o-')
        target = 'Order'
      else if (this.searchEntry.slice(0, 2) == 'd-')
        target = 'Dataset'
      else if (this.searchEntry.slice(0, 2) == 'c-')
        target = 'Collection'
      else {
        target = ''
        this.searchError = true
        setTimeout(function(){ this.searchError = false }.bind(this), 800);
      }
      if (target.length)
        this.$router.push({ name: target + ' About', params: { 'uuid': this.searchEntry,
                                                               'dataType': target.toLowerCase()} });
    }
  }
}
</script>
