CREATE SCHEMA IF NOT EXISTS data;

CREATE TABLE IF NOT EXISTS data.datasets (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    study           integer                 NOT NULL REFERENCES data.studies,
    short_name      varchar(50)     UNIQUE  NOT NULL,
    full_name       varchar(100)            NOT NULL,
    browser_uri     varchar(200)            DEFAULT NULL,
    beacon_uri      varchar(200)            DEFAULT NULL,
    beacon_description text                 DEFAULT NULL,
    avg_seq_depth   real                    DEFAULT NULL,
    seq_type        varchar(50)             DEFAULT NULL,
    seq_tech        varchar(50)             DEFAULT NULL,
    seq_center      varchar(100)            DEFAULT NULL,
    dataset_size    integer                 NOT NULL CHECK (dataset_size >= 0)
);

--------------------------------------------------------------------------------
-- Indexes
--
