CREATE SCHEMA IF NOT EXISTS project_data;

CREATE TABLE IF NOT EXISTS project_data.datasets (
    id 	     	    integer		    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           varchar(100)            NOT NULL,
    description     text                    DEFAULT NULL,
    doi             varchar(60)             DEFAULT NULL,
    creator         varchar(50)             DEFAULT NULL,
    dmp             varchar(100)            DEFAULT NULL,
    visible         boolean                 NOT NULL
);

CREATE TABLE IF NOT EXISTS project_data.data_urls (
    id 	     	    integer		    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url             varchar(200)            DEFAULT NULL,
    description     varchar(100)            DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS project_data.dataset_data_url_map (
    dataset_id      integer                 NOT NULL REFERENCES project_data.datasets ON DELETE CASCADE,
    data_url_id     integer                 NOT NULL REFERENCES project_data.data_urls,
    PRIMARY KEY(dataset_id, data_url_id)
);

CREATE TABLE IF NOT EXISTS project_data.projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           varchar(100)            NOT NULL,
    description     text                    DEFAULT NULL,
    contact         varchar(100)            DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS project_data.project_dataset_map (
    project_id      integer                 NOT NULL REFERENCES project_data.projects,
    dataset_id      integer                 NOT NULL REFERENCES project_data.datasets ON DELETE CASCADE,
    PRIMARY KEY(dataset_id, project_id)
);

CREATE TABLE IF NOT EXISTS project_data.publications (
    id              integer                 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    identifier      text                    NOT NULL
);

CREATE TABLE IF NOT EXISTS project_data.dataset_publication_map (
    dataset_id      integer                 NOT NULL REFERENCES project_data.datasets ON DELETE CASCADE,
    publication_id  integer                 NOT NULL REFERENCES project_data.publications,
    PRIMARY KEY(dataset_id, publication_id)
);

CREATE TABLE IF NOT EXISTS project_data.tags (
    id              integer                 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           varchar(100)            NOT NULL
);

CREATE TABLE IF NOT EXISTS project_data.dataset_tag_map (
    dataset_id      integer                 NOT NULL REFERENCES project_data.datasets ON DELETE CASCADE,
    tag_id          integer                 NOT NULL REFERENCES project_data.tags,
    PRIMARY KEY(dataset_id, tag_id)
);


--------------------------------------------------------------------------------
-- Indexes
--
