name: Publish Docker image
on:
  push:
    branches:
      - develop
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: k8s/Dockerfile.backend
          context: .
          push: true
          tags: scilifelabdatacentre/data-tracker-backend:dev
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: k8s/Dockerfile.frontend
          context: .
          push: true
          tags: scilifelabdatacentre/data-tracker-frontend:dev
