name: Publish Docker Image
on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'ScilifelabDataCentre/Data-Tracker'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      # prepare qemu and buildx to enable multi-architecture builds
      - name: Run setup-qemu-action
        uses: docker/setup-qemu-action@v2
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # available in scilifelabdatacentre, ask admin for help
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}}
      # only needed when publishing to Github (ghcr.io)
      - name: Log in to Github Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # will run as the user who triggered the action, using its token
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta - Backend
        id: meta-backend
        uses: docker/metadata-action@v4
        with:
          images: |
            scilifelabdatacentre/data-tracker-backend
            ghcr.io/scilifelabdatacentre/data-tracker-backend
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker Meta - Frontend
        id: meta-frontend
        uses: docker/metadata-action@v4
        with:
          images: |
            scilifelabdatacentre/data-tracker-frontend
            ghcr.io/scilifelabdatacentre/data-tracker-frontend
      - name: Build and Publish Backend
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.backend
          context: .
          push: true
          target: production
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
      - name: Build and Publish Frontend
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.frontend
          context: .
          target: production
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
