---
name: Black formatting
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  BlackFormatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code lints with Black
        uses: jpetrucciani/black-check@master
        with:
          black_flags: '-l 100'
